### ISSUE TITLE
怎么编译dlib.so

### ISSUE THREAD

**Issue by yeshiyuan00** [weank1984/face-recognition#2]
你好，请问下你的dlib是怎么编译成so的？求教！

**Comment by weank1984** [comment]
@yeshiyuan00 dlib的so编译可以参考[dlib_anroid](https://github.com/tzutalin/dlib-android),这个只支持了人脸检测，我在里面添加了人脸辨识。

- 如果你想实现人脸识别的话需要将dlib版本升级到至少19.4。

- 人脸辨识部分请参考[dlib-face-example](http://dlib.net/dnn_face_recognition_ex.cpp.html)

- dlib使用ndk编译的时候会有部分函数报错，需要你修改。

- android.mk文件中要添加部分必要的文件。

**Comment by yeshiyuan00** [comment]
好的，十分感谢！！
